CREATE TABLE carta
(
    id                      INT           NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fecha_creacion          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    numero_expediente       VARCHAR(255)  NOT NULL,
    nombre_cliente          VARCHAR(255)  NOT NULL,
    calle                   VARCHAR(255)  NOT NULL,
    cruzamientos            VARCHAR(255)  NOT NULL,
    numero_direccion        VARCHAR(255)  NOT NULL,
    colonia_fraccionamiento VARCHAR(255)  NOT NULL,
    localidad               VARCHAR(255)  NOT NULL,
    municipio               VARCHAR(255)  NOT NULL,
    fecha_firma             DATE          NOT NULL,
    documentacion           TEXT,
    comprobacion_monto      FLOAT(200, 2) NOT NULL,
    comprobacion_tipo       VARCHAR(255)  NOT NULL,
    pagos_fecha_inicial     VARCHAR(255)  NOT NULL,
    pagos_fecha_final       VARCHAR(255)  NOT NULL,
    tipo_credito            VARCHAR(255)  NOT NULL,
    fecha_otorgamiento      DATE          NOT NULL,
    monto_inicial           FLOAT(200, 2) NOT NULL,
    mensualidades_vencidas  INT           NOT NULL,
    adeudo_total            FLOAT(200, 2) NOT NULL,
    nombre_archivo          VARCHAR(255)
);

CREATE TABLE bitacora
(
    id                              INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fecha_creacion                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    acreditado_nombre               VARCHAR(255) NOT NULL,
    acreditado_folio                VARCHAR(255) NOT NULL,
    acreditado_municipio            VARCHAR(255) NOT NULL,
    acreditado_garantia             VARCHAR(255) NOT NULL,
    acreditado_telefono             VARCHAR(255) NOT NULL,
    acreditado_email                VARCHAR(255) NOT NULL,
    acreditado_direccion_negocio    VARCHAR(255) NOT NULL,
    acreditado_direccion_particular VARCHAR(255) NOT NULL,
    aval_nombre                     VARCHAR(255),
    aval_telefono                   VARCHAR(255),
    aval_email                      VARCHAR(255),
    aval_direccion                  VARCHAR(255),
    gestion_fecha1                  DATE         NOT NULL,
    gestion_via1                    VARCHAR(255) NOT NULL,
    gestion_comentarios1            VARCHAR(255),
    gestion_fecha2                  DATE,
    gestion_via2                    VARCHAR(255),
    gestion_comentarios2            VARCHAR(255),
    gestion_fecha3                  DATE,
    gestion_via3                    VARCHAR(255),
    gestion_comentarios3            VARCHAR(255),
    gestion_fecha4                  DATE,
    gestion_via4                    VARCHAR(255),
    gestion_comentarios4            VARCHAR(255),
    gestion_fecha5                  DATE,
    gestion_via5                    VARCHAR(255),
    gestion_comentarios5            VARCHAR(255),
    gestion_fecha6                  DATE,
    gestion_via6                    VARCHAR(255),
    gestion_comentarios6            VARCHAR(255),
    gestion_fecha7                  DATE,
    gestion_via7                    VARCHAR(255),
    gestion_comentarios7            VARCHAR(255),
    gestion_fecha8                  DATE,
    gestion_via8                    VARCHAR(255),
    gestion_comentarios8            VARCHAR(255),
    gestion_fecha9                  DATE,
    gestion_via9                    VARCHAR(255),
    gestion_comentarios9            VARCHAR(255),
    gestion_fecha10                 DATE,
    gestion_via10                   VARCHAR(255),
    gestion_comentarios10           VARCHAR(255),
    gestion_fecha11                 DATE,
    gestion_via11                   VARCHAR(255),
    gestion_comentarios11           VARCHAR(255),
    gestion_fecha12                 DATE,
    gestion_via12                   VARCHAR(255),
    gestion_comentarios12           VARCHAR(255),
    gestion_contador                INT          NOT NULL,
    evidencia_fecha1                DATE,
    evidencia_fotografia1           VARCHAR(255),
    evidencia_fecha2                DATE,
    evidencia_fotografia2           VARCHAR(255),
    evidencia_fecha3                DATE,
    evidencia_fotografia3           VARCHAR(255),
    evidencia_fecha4                DATE,
    evidencia_fotografia4           VARCHAR(255),
    evidencia_fecha5                DATE,
    evidencia_fotografia5           VARCHAR(255),
    evidencia_fecha6                DATE,
    evidencia_fotografia6           VARCHAR(255),
    evidencia_fecha7                DATE,
    evidencia_fotografia7           VARCHAR(255),
    evidencia_fecha8                DATE,
    evidencia_fotografia8           VARCHAR(255),
    evidencia_fecha9                DATE,
    evidencia_fotografia9           VARCHAR(255),
    evidencia_fecha10               DATE,
    evidencia_fotografia10          VARCHAR(255),
    evidencia_fecha11               DATE,
    evidencia_fotografia11          VARCHAR(255),
    evidencia_fecha12               DATE,
    evidencia_fotografia12          VARCHAR(255),
    nombre_archivo                  VARCHAR(255) NOT NULL
);

CREATE TABLE usuario
(
    id       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre   VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

INSERT INTO usuario
VALUES (null, 'Admin', '123456789@MY');