CREATE TABLE carta
(
    id                      INT           NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fecha_creacion          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    numero_expediente       VARCHAR(255)  NOT NULL,
    nombre_cliente          VARCHAR(255)  NOT NULL,
    calle                   VARCHAR(255)  NOT NULL,
    cruzamientos            VARCHAR(255)  NOT NULL,
    numero_direccion        VARCHAR(255)  NOT NULL,
    colonia_fraccionamiento VARCHAR(255)  NOT NULL,
    localidad               VARCHAR(255)  NOT NULL,
    municipio               VARCHAR(255)  NOT NULL,
    fecha_firma             DATE          NOT NULL,
    documentacion           TEXT,
    comprobacion_monto      FLOAT(200, 2) NOT NULL,
    comprobacion_tipo       VARCHAR(255)  NOT NULL,
    pagos_fecha_inicial     VARCHAR(255)  NOT NULL,
    pagos_fecha_final       VARCHAR(255)  NOT NULL,
    tipo_credito            VARCHAR(255)  NOT NULL,
    fecha_otorgamiento      DATE          NOT NULL,
    monto_inicial           FLOAT(200, 2) NOT NULL,
    mensualidades_vencidas  INT           NOT NULL,
    adeudo_total            FLOAT(200, 2) NOT NULL,
    archivo                 VARCHAR(255)
);

CREATE TABLE bitacora
(
    id                   INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fecha_creacion       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    acreditado_nombre    VARCHAR(255) NOT NULL,
    folio                VARCHAR(255) NOT NULL,
    municipio            VARCHAR(255) NOT NULL,
    garantia             VARCHAR(255) NOT NULL,
    acreditado_telefono  VARCHAR(255) NOT NULL,
    acreditado_email     VARCHAR(255) NOT NULL,
    direccion_negocio    VARCHAR(255) NOT NULL,
    direccion_particular VARCHAR(255) NOT NULL,
    aval_nombre          VARCHAR(255),
    aval_telefono        VARCHAR(255),
    aval_email           VARCHAR(255),
    aval_direccion       VARCHAR(255),
    gestion_fecha1       DATE         NOT NULL,
    gestion_via1         VARCHAR(255) NOT NULL,
    gestion_comentarios1 VARCHAR(255) NOT NULL,
    gestion_fecha2       DATE,
    gestion_via2         VARCHAR(255),
    gestion_comentarios2 VARCHAR(255),
    gestion_fecha3       DATE,
    gestion_via3         VARCHAR(255),
    gestion_comentarios3 VARCHAR(255),
    gestion_fecha4       DATE,
    gestion_via4         VARCHAR(255),
    gestion_comentarios4 VARCHAR(255),
    gestion_fecha5       DATE,
    gestion_via5         VARCHAR(255),
    gestion_comentarios5 VARCHAR(255),
    evidencia_fecha      DATE         NOT NULL,
    evidencia_fotografia VARCHAR(255)
)